// Real Pittsburgh restaurant data from the Figma screenshot.
// Tagged with meal + cuisine so dropdown filters work.

const RESTAURANTS = [
  {
    id: 'square-cafe',
    name: 'Square Cafe',
    sponsored: true,
    rating: 5,
    reviews: 412,
    price: '$$',
    open: true,
    address: '134 S Highland Ave, Pittsburgh, PA 15206',
    meal: ['BREAKFAST', 'LUNCH'],
    cuisine: ['AMERICAN', 'COFFEE'],
    description:
      "Square Cafe is a bright, welcoming spot in Pittsburgh's East Liberty neighborhood serving fresh, seasonal dishes made with local ingredients. From creative breakfast plates to flavorful lunches, everything is made with care and a focus on quality.",
    image: 'assets/imagery/sq-plate.jpg',
    color: '#5a3a1f',
  },
  {
    id: 'italian-village',
    name: 'Italian Village Pizza',
    rating: 4,
    reviews: 308,
    price: '$',
    open: true,
    address: '4885 McKnight Road # 4, Pittsburgh',
    meal: ['LUNCH', 'DINNER'],
    cuisine: ['PIZZA', 'ITALIAN'],
    description: 'Neighborhood slice shop. Thick crust, generous toppings, no frills — a North Hills staple.',
    image: 'assets/imagery/iv-pies.jpg',
    color: '#6b4a20',
  },
  {
    id: 'mad-mex',
    name: 'Mad Mex',
    rating: 4.4,
    reviews: 1611,
    price: '$$',
    open: true,
    address: '7905 McKnight Road, Pittsburgh',
    meal: ['LUNCH', 'DINNER'],
    cuisine: ['MEXICAN', 'TACOS', 'VEGETARIAN'],
    description: 'Pittsburgh favorite since 1993. Big burritos, Big Azz margaritas, dependable Tex-Mex energy.',
    image: 'assets/imagery/mm-patio.jpg',
    color: '#4a2618',
  },
  {
    id: 'subway',
    name: 'Subway',
    rating: 4.4,
    reviews: 135,
    price: '$',
    open: true,
    address: '4525 McKnight Road, Pittsburgh',
    meal: ['LUNCH', 'DINNER'],
    cuisine: ['SANDWICHES', 'AMERICAN'],
    description: 'Fast, customizable subs. The reliable pick when you need something quick between stops.',
    image: 'assets/imagery/sw-sub.jpg',
    color: '#3a4a2e',
  },
  {
    id: 'npl-mccandless',
    name: 'North Park Lounge McCandless',
    rating: 4.4,
    reviews: 1985,
    price: '$$',
    open: true,
    address: '9400 McKnight Road, Pittsburgh',
    meal: ['LUNCH', 'DINNER'],
    cuisine: ['AMERICAN', 'BURGERS', 'SEAFOOD'],
    description: 'Classic American tavern menu — burgers, seafood, full bar, and sports on every screen.',
    image: 'assets/imagery/npl-ext.jpg',
    color: '#2a2a2a',
  },
  {
    id: 'primanti',
    name: 'Primanti Bros',
    rating: 4.3,
    reviews: 3201,
    price: '$',
    open: true,
    address: '46 18th St, Pittsburgh',
    meal: ['LUNCH', 'DINNER'],
    cuisine: ['SANDWICHES', 'AMERICAN'],
    description: 'Iconic Pittsburgh sandwich shop. Fries and slaw piled inside every sandwich — by design.',
    image: 'assets/imagery/pb-sand.jpg',
    color: '#553826',
  },
];

window.RESTAURANTS = RESTAURANTS;
